CREATE TABLE indiv(
CMTE_ID VARCHAR(9),
AMNDT_IND VARCHAR(1),
RPT_TP VARCHAR(3),
TRANSACTION_PGI VARCHAR(5),
IMAGE_NUM VARCHAR(18),
TRANSACTION_TP VARCHAR(3),
ENTITY_TP VARCHAR(3),
NAME VARCHAR(200),
CITY VARCHAR(30),
STATE VARCHAR(2),
ZIP_CODE VARCHAR(9),
EMPLOYER VARCHAR(38),
OCCUPATION VARCHAR(38),
TRANSACTION_DT VARCHAR(10),
TRANSACTION_AMT DECIMAL(14,2),
OTHER_ID VARCHAR(9),
TRAN_ID VARCHAR(32),
FILE_NUM BIGINT,
MEMO_CD VARCHAR(1),
MEMO_TEXT VARCHAR(100),
SUB_ID BIGINT,
cand_id VARCHAR(25)
)
;

LOAD DATA LOCAL INFILE 'C:\\Users\\ElizabethL\\Desktop\\NICAR17\\MySQL\\indiv.csv'
INTO TABLE indiv
FIELDS TERMINATED BY '|'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'
;