CREATE TABLE cand (
CAND_ID VARCHAR(9),
CAND_NAME VARCHAR(200),
CAND_PTY_AFFILIATION VARCHAR(3),
CAND_ELECTION_YR INT,
CAND_OFFICE_ST VARCHAR(2),
CAND_OFFICE VARCHAR(1),
CAND_OFFICE_DISTRICT VARCHAR(2),
CAND_ICI VARCHAR(1),
CAND_STATUS VARCHAR(1),
CAND_PCC VARCHAR(9),
CAND_ST1 VARCHAR(34),
CAND_ST2 VARCHAR(34),
CAND_CITY VARCHAR(30),
CAND_ST VARCHAR(2),
CAND_ZIP VARCHAR(9)
);

LOAD DATA LOCAL INFILE 'C:\\Users\\ElizabethL\\Desktop\\NICAR17\\MySQL\\cand.csv'
INTO TABLE cand
FIELDS TERMINATED BY '|'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'
;
